// Generated by scripts/dump-tools.mjs — do not edit by hand.
// Regenerate when the Local REST API plugin's tool surface changes.
export const OBSIDIAN_TOOLS = [
  {
    "name": "vault_list",
    "description": "List files and subdirectories inside a vault directory. Returns an array of names; directory entries end with '/'. Omit path or pass an empty string to list the vault root.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "Directory path relative to vault root (default: root)"
        }
      },
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_read",
    "description": "Read a vault file's content and metadata. Returns a JSON object with: content (full markdown text), path, tags (array of tag strings), frontmatter (parsed YAML front-matter as an object), stat ({ctime, mtime, size}), links (array of vault-relative paths this file links to), and backlinks (array of vault-relative paths of files that link here). Throws if the file does not exist.\n\nWhen targetType and target are both provided, returns only the matched section as a plain string (markdown) or JSON value (frontmatter) instead of the full object. Use vault_get_document_map first to discover available targets.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        },
        "targetType": {
          "type": "string",
          "enum": [
            "heading",
            "block",
            "frontmatter"
          ],
          "description": "Type of section to extract: 'heading', 'block' reference, or 'frontmatter' key"
        },
        "target": {
          "type": "string",
          "description": "Section to extract. Heading text, block reference ID (without '^'), or frontmatter key. Separate nested heading levels with '::' (e.g. 'Heading 1::Subheading')."
        },
        "targetDelimiter": {
          "type": "string",
          "description": "Delimiter for nested heading paths (default: '::')"
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_write",
    "description": "Create or overwrite a vault file with the given content. Creates any missing parent directories automatically. Overwrites without warning if the file already exists.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        },
        "content": {
          "type": "string",
          "description": "Full file content (markdown text)"
        }
      },
      "required": [
        "path",
        "content"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_append",
    "description": "Append content to the end of a vault file. Creates the file if it does not already exist.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        },
        "content": {
          "type": "string",
          "description": "Content to append"
        }
      },
      "required": [
        "path",
        "content"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_patch",
    "description": "Patch a specific section of a vault file by targeting a heading, block reference, or frontmatter field.\n\n- targetType: 'heading' targets the content beneath a markdown heading (the heading line itself is not part of the section and must not appear in the supplied content); 'block' targets a block reference (the ID after '^'); 'frontmatter' targets a YAML front-matter key.\n- target: the heading text, block ID, or frontmatter key. For nested headings use '::' as delimiter (e.g. 'Heading 1::Subheading'); customise with targetDelimiter.\n- operation: 'append' adds content after the section, 'prepend' adds before, 'replace' replaces entirely.\n- contentType: 'text/markdown' (default) treats content as markdown. 'application/json' parses it as JSON — useful for setting typed frontmatter values or appending rows to a table (pass a 2-D array of row cells).\n- createTargetIfMissing: set to true to create the heading or frontmatter key if it does not exist yet.\n- trimTargetWhitespace: strip leading/trailing whitespace from the target section before patching.\n- rejectIfContentPreexists: fail the patch if the content string already appears in the target section — use this as an idempotency guard so a retry does not duplicate content.\n- targetScope: controls what portion of the target the operation acts on. 'content' (default) patches only the content below the heading or at the block; 'marker' patches only the heading line or block-ID token itself; 'markerAndContent' patches the heading/block-ID together with its content. Only applicable to heading and block targets.\n\nTo discover valid heading names and block IDs before patching, call vault_get_document_map first.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        },
        "targetType": {
          "type": "string",
          "enum": [
            "heading",
            "block",
            "frontmatter"
          ],
          "description": "Type of target section: 'heading', 'block' reference, or 'frontmatter' key"
        },
        "target": {
          "type": "string",
          "description": "The section to patch. Heading text, block reference ID (without '^'), or frontmatter key. Separate nested heading levels with '::' (e.g. 'Heading 1::Subheading')."
        },
        "operation": {
          "type": "string",
          "enum": [
            "replace",
            "prepend",
            "append"
          ],
          "description": "How to apply the content: replace the section, prepend before it, or append after it"
        },
        "content": {
          "description": "Content to apply. For contentType 'text/markdown' pass a string. For contentType 'application/json' you may pass a native JSON value (number, boolean, array, object) and it will be serialised automatically."
        },
        "contentType": {
          "type": "string",
          "description": "MIME type of content. 'text/markdown' (default) or 'application/json'. Use 'application/json' to set typed frontmatter values or to append/prepend table rows (2-D array)."
        },
        "createTargetIfMissing": {
          "type": "boolean",
          "description": "Create the heading or frontmatter key if it does not already exist (default: false)"
        },
        "trimTargetWhitespace": {
          "type": "boolean",
          "description": "Trim whitespace from the target section before applying the operation (default: false)"
        },
        "rejectIfContentPreexists": {
          "type": "boolean",
          "description": "If true, fail the patch when the content already appears in the target section (default: false). Use to make append/prepend operations idempotent on retry."
        },
        "targetDelimiter": {
          "type": "string",
          "description": "Delimiter for nested heading paths (default: '::')"
        },
        "targetScope": {
          "type": "string",
          "enum": [
            "content",
            "marker",
            "markerAndContent"
          ],
          "description": "Controls which part of the target the operation acts on. 'content' (default): patch the content below the heading or at the block. 'marker': patch only the heading line or block-ID token. 'markerAndContent': patch the heading/block-ID together with its content. Only applicable to heading and block targets."
        }
      },
      "required": [
        "path",
        "targetType",
        "target",
        "operation"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_delete",
    "description": "Delete a file from the vault. Throws if the file does not exist.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "vault_get_document_map",
    "description": "Return the structure of a vault file as a document map: the list of heading paths, block reference IDs, and frontmatter field names present in the file. Use this before vault_read or vault_patch with targeting to discover what targets are available without parsing the full markdown content yourself.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "active_file_get_path",
    "description": "Return the vault-relative path of the file currently open in Obsidian. Use this path with vault_read, vault_write, vault_append, vault_patch, vault_get_document_map, or vault_delete to operate on the active file. Throws if no file is active.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "periodic_note_get_path",
    "description": "Return the vault-relative path of the current periodic note for the given period (daily, weekly, monthly, quarterly, or yearly). Creates the note file if it does not already exist, applying any configured template. Requires the Periodic Notes or Calendar plugin to be installed and configured. Use the returned path with vault_read, vault_write, vault_append, vault_patch, or vault_get_document_map to operate on the note.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "period": {
          "type": "string",
          "enum": [
            "daily",
            "weekly",
            "monthly",
            "quarterly",
            "yearly"
          ],
          "description": "Periodic note period: 'daily', 'weekly', 'monthly', 'quarterly', or 'yearly'"
        }
      },
      "required": [
        "period"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "search_query",
    "description": "Search vault files using a JsonLogic query evaluated against each note's metadata.\n\nThe query is a JSON object following the JsonLogic spec (https://jsonlogic.com/operations.html). It is evaluated against a NoteJson object for each file; files where the result is truthy are returned.\n\nEach NoteJson has: path (string), content (string), tags (string[]), frontmatter (object), stat ({ctime, mtime, size}), links (string[]), backlinks (string[]).\n\nExtra operators available beyond standard JsonLogic:\n- {\"glob\": [\"*.foo\", {\"var\": \"path\"}]} — glob pattern match\n- {\"regexp\": [\"^daily/\", {\"var\": \"path\"}]} — regular expression match\n\nReturns an array of {filename, result} objects where result is the truthy value the query produced for that file.\n\nExamples:\n- Find by tag: {\"in\": [\"myTag\", {\"var\": \"tags\"}]}\n- Find by frontmatter field: {\"==\": [{\"var\": \"frontmatter.status\"}, \"done\"]}\n- Find by path glob: {\"glob\": [\"journal/*\", {\"var\": \"path\"}]}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "object",
          "additionalProperties": {},
          "description": "JsonLogic query object to evaluate against each note"
        }
      },
      "required": [
        "query"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "search_simple",
    "description": "Search vault files using Obsidian's built-in simple search. Returns an array of {filename, score, matches} objects sorted by relevance score. Each match includes the matched text and surrounding context characters (controlled by contextLength).",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "description": "Search query string"
        },
        "contextLength": {
          "type": "number",
          "description": "Number of characters of surrounding context to return per match (default: 100)"
        }
      },
      "required": [
        "query"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "tag_list",
    "description": "Return all tags used across the vault, each with a usage count. Tag names do not include the leading '#'. This tool is read-only. To add a tag to a specific file, use vault_patch with targetType 'frontmatter', target 'tags', operation 'append', contentType 'application/json', and content [\"tag-name\"] (set createTargetIfMissing to true if the file may have no tags yet). To remove a tag, read the current tags list with vault_read, filter client-side, then replace the whole field with vault_patch using operation 'replace'. For full examples, read the OpenAPI spec resource at obsidian://local-rest-api/openapi.yaml.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "command_list",
    "description": "Return all registered Obsidian commands. Each entry has an 'id' and a human-readable 'name'. Pass the 'id' to command_execute to run a command.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "command_execute",
    "description": "Execute an Obsidian command by its ID. Use command_list to discover available command IDs. Throws if the command ID does not exist.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "commandId": {
          "type": "string",
          "description": "The command ID to execute (e.g. 'editor:toggle-bold')"
        }
      },
      "required": [
        "commandId"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  },
  {
    "name": "open_file",
    "description": "Open a file in the Obsidian UI. If the file does not exist, Obsidian will create a new document at that path. Set newLeaf to true to open in a new pane rather than the current one.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string",
          "description": "File path relative to vault root"
        },
        "newLeaf": {
          "type": "boolean",
          "description": "Open in a new leaf/pane (default: false)"
        }
      },
      "required": [
        "path"
      ],
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-07/schema#"
    },
    "execution": {
      "taskSupport": "forbidden"
    }
  }
];
