import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const url = process.env.OBSIDIAN_MCP_URL ?? "https://127.0.0.1:27124/mcp/";
const apiKey = process.env.OBSIDIAN_API_KEY;
if (!apiKey) {
  console.error("Set OBSIDIAN_API_KEY (and optionally OBSIDIAN_MCP_URL).");
  process.exit(1);
}

const client = new Client(
  { name: "dump-tools", version: "0.0.0" },
  { capabilities: {} },
);
const transport = new StreamableHTTPClientTransport(new URL(url), {
  requestInit: { headers: { Authorization: `Bearer ${apiKey}` } },
});
await client.connect(transport);
const result = await client.listTools();
process.stdout.write("// Generated by scripts/dump-tools.mjs — do not edit by hand.\n");
process.stdout.write("// Regenerate when the Local REST API plugin's tool surface changes.\n");
process.stdout.write(`export const OBSIDIAN_TOOLS = ${JSON.stringify(result.tools, null, 2)};\n`);
await client.close();
